source "https://rubygems.org"
#
#  Instructions: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll
#  Supported dependency versions: https://pages.github.com/versions/
#
gem "github-pages", "~> 228", group: :jekyll_plugins

gem "webrick"
